// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/discopass.proto

// Paquete de Protocol Buffers para el laboratorio DiscoPass.
// Aqui se definen TODOS los mensajes y servicios que viajan por gRPC
// entre las entidades del sistema (broker, productores, nodos DB,
// banco y consumidores).

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vacio: peticion/respuesta sin datos (cuando no hace falta enviar nada).
type Vacio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	mi := &file_proto_discopass_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{0}
}

// Ack: respuesta generica de confirmacion (ok/no + un mensaje explicativo).
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_discopass_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// Registro: una entidad se identifica ante el broker antes de operar.
// tipo = "discoteca" | "usuario" | "db" | "banco".
type Registro struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo          string                 `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registro) Reset() {
	*x = Registro{}
	mi := &file_proto_discopass_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registro) ProtoMessage() {}

func (x *Registro) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registro.ProtoReflect.Descriptor instead.
func (*Registro) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{2}
}

func (x *Registro) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Registro) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

// ----------------------------------------------------------------------------
// Evento (la "entrada"/fiesta que publica una discoteca)
// ----------------------------------------------------------------------------
type Evento struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventoId         string                 `protobuf:"bytes,1,opt,name=evento_id,json=eventoId,proto3" json:"evento_id,omitempty"` // UUIDv4 unico -> permite idempotencia
	Discoteca        string                 `protobuf:"bytes,2,opt,name=discoteca,proto3" json:"discoteca,omitempty"`               // nombre de la discoteca productora
	NombreEvento     string                 `protobuf:"bytes,3,opt,name=nombre_evento,json=nombreEvento,proto3" json:"nombre_evento,omitempty"`
	Categoria        string                 `protobuf:"bytes,4,opt,name=categoria,proto3" json:"categoria,omitempty"` // debe pertenecer a la lista de categorias validas
	Comuna           string                 `protobuf:"bytes,5,opt,name=comuna,proto3" json:"comuna,omitempty"`
	Precio           int64                  `protobuf:"varint,6,opt,name=precio,proto3" json:"precio,omitempty"`
	Stock            int64                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"` // entradas disponibles (debe ser > 0)
	FechaEvento      string                 `protobuf:"bytes,8,opt,name=fecha_evento,json=fechaEvento,proto3" json:"fecha_evento,omitempty"`
	FechaPublicacion string                 `protobuf:"bytes,9,opt,name=fecha_publicacion,json=fechaPublicacion,proto3" json:"fecha_publicacion,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Evento) Reset() {
	*x = Evento{}
	mi := &file_proto_discopass_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evento) ProtoMessage() {}

func (x *Evento) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evento.ProtoReflect.Descriptor instead.
func (*Evento) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{3}
}

func (x *Evento) GetEventoId() string {
	if x != nil {
		return x.EventoId
	}
	return ""
}

func (x *Evento) GetDiscoteca() string {
	if x != nil {
		return x.Discoteca
	}
	return ""
}

func (x *Evento) GetNombreEvento() string {
	if x != nil {
		return x.NombreEvento
	}
	return ""
}

func (x *Evento) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *Evento) GetComuna() string {
	if x != nil {
		return x.Comuna
	}
	return ""
}

func (x *Evento) GetPrecio() int64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Evento) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Evento) GetFechaEvento() string {
	if x != nil {
		return x.FechaEvento
	}
	return ""
}

func (x *Evento) GetFechaPublicacion() string {
	if x != nil {
		return x.FechaPublicacion
	}
	return ""
}

// Respuesta del broker al productor cuando publica un evento.
type PublicarResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aceptado      bool                   `protobuf:"varint,1,opt,name=aceptado,proto3" json:"aceptado,omitempty"`
	Motivo        string                 `protobuf:"bytes,2,opt,name=motivo,proto3" json:"motivo,omitempty"` // razon de rechazo (categoria invalida, duplicado, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicarResp) Reset() {
	*x = PublicarResp{}
	mi := &file_proto_discopass_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicarResp) ProtoMessage() {}

func (x *PublicarResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicarResp.ProtoReflect.Descriptor instead.
func (*PublicarResp) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{4}
}

func (x *PublicarResp) GetAceptado() bool {
	if x != nil {
		return x.Aceptado
	}
	return false
}

func (x *PublicarResp) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

// ----------------------------------------------------------------------------
// Consultas y compras de los usuarios
// ----------------------------------------------------------------------------
type ConsultaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario     string                 `protobuf:"bytes,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultaReq) Reset() {
	*x = ConsultaReq{}
	mi := &file_proto_discopass_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultaReq) ProtoMessage() {}

func (x *ConsultaReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultaReq.ProtoReflect.Descriptor instead.
func (*ConsultaReq) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{5}
}

func (x *ConsultaReq) GetIdUsuario() string {
	if x != nil {
		return x.IdUsuario
	}
	return ""
}

type ListaEventos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eventos       []*Evento              `protobuf:"bytes,1,rep,name=eventos,proto3" json:"eventos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaEventos) Reset() {
	*x = ListaEventos{}
	mi := &file_proto_discopass_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaEventos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaEventos) ProtoMessage() {}

func (x *ListaEventos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaEventos.ProtoReflect.Descriptor instead.
func (*ListaEventos) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{6}
}

func (x *ListaEventos) GetEventos() []*Evento {
	if x != nil {
		return x.Eventos
	}
	return nil
}

type CompraReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario     string                 `protobuf:"bytes,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	EventoId      string                 `protobuf:"bytes,2,opt,name=evento_id,json=eventoId,proto3" json:"evento_id,omitempty"`
	MedioPago     string                 `protobuf:"bytes,3,opt,name=medio_pago,json=medioPago,proto3" json:"medio_pago,omitempty"` // "debito", "credito", "efectivo", ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompraReq) Reset() {
	*x = CompraReq{}
	mi := &file_proto_discopass_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompraReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompraReq) ProtoMessage() {}

func (x *CompraReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompraReq.ProtoReflect.Descriptor instead.
func (*CompraReq) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{7}
}

func (x *CompraReq) GetIdUsuario() string {
	if x != nil {
		return x.IdUsuario
	}
	return ""
}

func (x *CompraReq) GetEventoId() string {
	if x != nil {
		return x.EventoId
	}
	return ""
}

func (x *CompraReq) GetMedioPago() string {
	if x != nil {
		return x.MedioPago
	}
	return ""
}

type CompraResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aprobada      bool                   `protobuf:"varint,1,opt,name=aprobada,proto3" json:"aprobada,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"` // solo si la compra fue aprobada
	Motivo        string                 `protobuf:"bytes,3,opt,name=motivo,proto3" json:"motivo,omitempty"`                     // razon de rechazo o estado (pendiente, sin stock, ...)
	NombreEvento  string                 `protobuf:"bytes,4,opt,name=nombre_evento,json=nombreEvento,proto3" json:"nombre_evento,omitempty"`
	Precio        int64                  `protobuf:"varint,5,opt,name=precio,proto3" json:"precio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompraResp) Reset() {
	*x = CompraResp{}
	mi := &file_proto_discopass_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompraResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompraResp) ProtoMessage() {}

func (x *CompraResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompraResp.ProtoReflect.Descriptor instead.
func (*CompraResp) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{8}
}

func (x *CompraResp) GetAprobada() bool {
	if x != nil {
		return x.Aprobada
	}
	return false
}

func (x *CompraResp) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *CompraResp) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

func (x *CompraResp) GetNombreEvento() string {
	if x != nil {
		return x.NombreEvento
	}
	return ""
}

func (x *CompraResp) GetPrecio() int64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

// ----------------------------------------------------------------------------
// Tickets e historial
// ----------------------------------------------------------------------------
type Ticket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"` // identificador unico generado por el broker
	IdUsuario     string                 `protobuf:"bytes,2,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	EventoId      string                 `protobuf:"bytes,3,opt,name=evento_id,json=eventoId,proto3" json:"evento_id,omitempty"`
	NombreEvento  string                 `protobuf:"bytes,4,opt,name=nombre_evento,json=nombreEvento,proto3" json:"nombre_evento,omitempty"`
	Precio        int64                  `protobuf:"varint,5,opt,name=precio,proto3" json:"precio,omitempty"`
	FechaCompra   string                 `protobuf:"bytes,6,opt,name=fecha_compra,json=fechaCompra,proto3" json:"fecha_compra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_proto_discopass_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{9}
}

func (x *Ticket) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *Ticket) GetIdUsuario() string {
	if x != nil {
		return x.IdUsuario
	}
	return ""
}

func (x *Ticket) GetEventoId() string {
	if x != nil {
		return x.EventoId
	}
	return ""
}

func (x *Ticket) GetNombreEvento() string {
	if x != nil {
		return x.NombreEvento
	}
	return ""
}

func (x *Ticket) GetPrecio() int64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Ticket) GetFechaCompra() string {
	if x != nil {
		return x.FechaCompra
	}
	return ""
}

type HistorialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario     string                 `protobuf:"bytes,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistorialReq) Reset() {
	*x = HistorialReq{}
	mi := &file_proto_discopass_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistorialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistorialReq) ProtoMessage() {}

func (x *HistorialReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistorialReq.ProtoReflect.Descriptor instead.
func (*HistorialReq) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{10}
}

func (x *HistorialReq) GetIdUsuario() string {
	if x != nil {
		return x.IdUsuario
	}
	return ""
}

type ListaTickets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*Ticket              `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaTickets) Reset() {
	*x = ListaTickets{}
	mi := &file_proto_discopass_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaTickets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaTickets) ProtoMessage() {}

func (x *ListaTickets) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaTickets.ProtoReflect.Descriptor instead.
func (*ListaTickets) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{11}
}

func (x *ListaTickets) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

// ----------------------------------------------------------------------------
// Banco USM (servicio de pago simulado)
// ----------------------------------------------------------------------------
type PagoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario     string                 `protobuf:"bytes,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	Monto         int64                  `protobuf:"varint,2,opt,name=monto,proto3" json:"monto,omitempty"`
	MedioPago     string                 `protobuf:"bytes,3,opt,name=medio_pago,json=medioPago,proto3" json:"medio_pago,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagoReq) Reset() {
	*x = PagoReq{}
	mi := &file_proto_discopass_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagoReq) ProtoMessage() {}

func (x *PagoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagoReq.ProtoReflect.Descriptor instead.
func (*PagoReq) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{12}
}

func (x *PagoReq) GetIdUsuario() string {
	if x != nil {
		return x.IdUsuario
	}
	return ""
}

func (x *PagoReq) GetMonto() int64 {
	if x != nil {
		return x.Monto
	}
	return 0
}

func (x *PagoReq) GetMedioPago() string {
	if x != nil {
		return x.MedioPago
	}
	return ""
}

type PagoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aprobado      bool                   `protobuf:"varint,1,opt,name=aprobado,proto3" json:"aprobado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagoResp) Reset() {
	*x = PagoResp{}
	mi := &file_proto_discopass_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagoResp) ProtoMessage() {}

func (x *PagoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagoResp.ProtoReflect.Descriptor instead.
func (*PagoResp) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{13}
}

func (x *PagoResp) GetAprobado() bool {
	if x != nil {
		return x.Aprobado
	}
	return false
}

// DBItem: una unidad de informacion a replicar (un evento o un ticket).
type DBItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tipo          string                 `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"` // "evento" | "ticket"
	Evento        *Evento                `protobuf:"bytes,2,opt,name=evento,proto3" json:"evento,omitempty"`
	Ticket        *Ticket                `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBItem) Reset() {
	*x = DBItem{}
	mi := &file_proto_discopass_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBItem) ProtoMessage() {}

func (x *DBItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBItem.ProtoReflect.Descriptor instead.
func (*DBItem) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{14}
}

func (x *DBItem) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *DBItem) GetEvento() *Evento {
	if x != nil {
		return x.Evento
	}
	return nil
}

func (x *DBItem) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

// Backlog: estado completo (eventos + tickets) que un nodo pide al broker
// cuando se reincorpora tras una caida, para resincronizarse.
type BacklogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdNodo        string                 `protobuf:"bytes,1,opt,name=id_nodo,json=idNodo,proto3" json:"id_nodo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BacklogReq) Reset() {
	*x = BacklogReq{}
	mi := &file_proto_discopass_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacklogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacklogReq) ProtoMessage() {}

func (x *BacklogReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacklogReq.ProtoReflect.Descriptor instead.
func (*BacklogReq) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{15}
}

func (x *BacklogReq) GetIdNodo() string {
	if x != nil {
		return x.IdNodo
	}
	return ""
}

type Backlog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eventos       []*Evento              `protobuf:"bytes,1,rep,name=eventos,proto3" json:"eventos,omitempty"`
	Tickets       []*Ticket              `protobuf:"bytes,2,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backlog) Reset() {
	*x = Backlog{}
	mi := &file_proto_discopass_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backlog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backlog) ProtoMessage() {}

func (x *Backlog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discopass_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backlog.ProtoReflect.Descriptor instead.
func (*Backlog) Descriptor() ([]byte, []int) {
	return file_proto_discopass_proto_rawDescGZIP(), []int{16}
}

func (x *Backlog) GetEventos() []*Evento {
	if x != nil {
		return x.Eventos
	}
	return nil
}

func (x *Backlog) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

var File_proto_discopass_proto protoreflect.FileDescriptor

const file_proto_discopass_proto_rawDesc = "" +
	"\n" +
	"\x15proto/discopass.proto\x12\tdiscopass\"\a\n" +
	"\x05Vacio\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\".\n" +
	"\bRegistro\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04tipo\x18\x02 \x01(\tR\x04tipo\"\x9c\x02\n" +
	"\x06Evento\x12\x1b\n" +
	"\tevento_id\x18\x01 \x01(\tR\beventoId\x12\x1c\n" +
	"\tdiscoteca\x18\x02 \x01(\tR\tdiscoteca\x12#\n" +
	"\rnombre_evento\x18\x03 \x01(\tR\fnombreEvento\x12\x1c\n" +
	"\tcategoria\x18\x04 \x01(\tR\tcategoria\x12\x16\n" +
	"\x06comuna\x18\x05 \x01(\tR\x06comuna\x12\x16\n" +
	"\x06precio\x18\x06 \x01(\x03R\x06precio\x12\x14\n" +
	"\x05stock\x18\a \x01(\x03R\x05stock\x12!\n" +
	"\ffecha_evento\x18\b \x01(\tR\vfechaEvento\x12+\n" +
	"\x11fecha_publicacion\x18\t \x01(\tR\x10fechaPublicacion\"B\n" +
	"\fPublicarResp\x12\x1a\n" +
	"\baceptado\x18\x01 \x01(\bR\baceptado\x12\x16\n" +
	"\x06motivo\x18\x02 \x01(\tR\x06motivo\",\n" +
	"\vConsultaReq\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x01 \x01(\tR\tidUsuario\";\n" +
	"\fListaEventos\x12+\n" +
	"\aeventos\x18\x01 \x03(\v2\x11.discopass.EventoR\aeventos\"f\n" +
	"\tCompraReq\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x01 \x01(\tR\tidUsuario\x12\x1b\n" +
	"\tevento_id\x18\x02 \x01(\tR\beventoId\x12\x1d\n" +
	"\n" +
	"medio_pago\x18\x03 \x01(\tR\tmedioPago\"\x9a\x01\n" +
	"\n" +
	"CompraResp\x12\x1a\n" +
	"\baprobada\x18\x01 \x01(\bR\baprobada\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x16\n" +
	"\x06motivo\x18\x03 \x01(\tR\x06motivo\x12#\n" +
	"\rnombre_evento\x18\x04 \x01(\tR\fnombreEvento\x12\x16\n" +
	"\x06precio\x18\x05 \x01(\x03R\x06precio\"\xc1\x01\n" +
	"\x06Ticket\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x02 \x01(\tR\tidUsuario\x12\x1b\n" +
	"\tevento_id\x18\x03 \x01(\tR\beventoId\x12#\n" +
	"\rnombre_evento\x18\x04 \x01(\tR\fnombreEvento\x12\x16\n" +
	"\x06precio\x18\x05 \x01(\x03R\x06precio\x12!\n" +
	"\ffecha_compra\x18\x06 \x01(\tR\vfechaCompra\"-\n" +
	"\fHistorialReq\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x01 \x01(\tR\tidUsuario\";\n" +
	"\fListaTickets\x12+\n" +
	"\atickets\x18\x01 \x03(\v2\x11.discopass.TicketR\atickets\"]\n" +
	"\aPagoReq\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x01 \x01(\tR\tidUsuario\x12\x14\n" +
	"\x05monto\x18\x02 \x01(\x03R\x05monto\x12\x1d\n" +
	"\n" +
	"medio_pago\x18\x03 \x01(\tR\tmedioPago\"&\n" +
	"\bPagoResp\x12\x1a\n" +
	"\baprobado\x18\x01 \x01(\bR\baprobado\"r\n" +
	"\x06DBItem\x12\x12\n" +
	"\x04tipo\x18\x01 \x01(\tR\x04tipo\x12)\n" +
	"\x06evento\x18\x02 \x01(\v2\x11.discopass.EventoR\x06evento\x12)\n" +
	"\x06ticket\x18\x03 \x01(\v2\x11.discopass.TicketR\x06ticket\"%\n" +
	"\n" +
	"BacklogReq\x12\x17\n" +
	"\aid_nodo\x18\x01 \x01(\tR\x06idNodo\"c\n" +
	"\aBacklog\x12+\n" +
	"\aeventos\x18\x01 \x03(\v2\x11.discopass.EventoR\aeventos\x12+\n" +
	"\atickets\x18\x02 \x03(\v2\x11.discopass.TicketR\atickets2\x88\x03\n" +
	"\x06Broker\x127\n" +
	"\x10RegistrarEntidad\x12\x13.discopass.Registro\x1a\x0e.discopass.Ack\x12<\n" +
	"\x0ePublicarEvento\x12\x11.discopass.Evento\x1a\x17.discopass.PublicarResp\x12C\n" +
	"\x10ConsultarEventos\x12\x16.discopass.ConsultaReq\x1a\x17.discopass.ListaEventos\x12=\n" +
	"\x0eComprarEntrada\x12\x14.discopass.CompraReq\x1a\x15.discopass.CompraResp\x12D\n" +
	"\x10ObtenerHistorial\x12\x17.discopass.HistorialReq\x1a\x17.discopass.ListaTickets\x12=\n" +
	"\x10SolicitarBacklog\x12\x15.discopass.BacklogReq\x1a\x12.discopass.Backlog2\xdd\x01\n" +
	"\x06NodoDB\x12-\n" +
	"\bEscribir\x12\x11.discopass.DBItem\x1a\x0e.discopass.Ack\x128\n" +
	"\vLeerEventos\x12\x10.discopass.Vacio\x1a\x17.discopass.ListaEventos\x12?\n" +
	"\vLeerTickets\x12\x17.discopass.HistorialReq\x1a\x17.discopass.ListaTickets\x12)\n" +
	"\x05Salud\x12\x10.discopass.Vacio\x1a\x0e.discopass.Ack2?\n" +
	"\x05Banco\x126\n" +
	"\vValidarPago\x12\x12.discopass.PagoReq\x1a\x13.discopass.PagoRespB\x14Z\x12discopass/proto;pbb\x06proto3"

var (
	file_proto_discopass_proto_rawDescOnce sync.Once
	file_proto_discopass_proto_rawDescData []byte
)

func file_proto_discopass_proto_rawDescGZIP() []byte {
	file_proto_discopass_proto_rawDescOnce.Do(func() {
		file_proto_discopass_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_discopass_proto_rawDesc), len(file_proto_discopass_proto_rawDesc)))
	})
	return file_proto_discopass_proto_rawDescData
}

var file_proto_discopass_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_discopass_proto_goTypes = []any{
	(*Vacio)(nil),        // 0: discopass.Vacio
	(*Ack)(nil),          // 1: discopass.Ack
	(*Registro)(nil),     // 2: discopass.Registro
	(*Evento)(nil),       // 3: discopass.Evento
	(*PublicarResp)(nil), // 4: discopass.PublicarResp
	(*ConsultaReq)(nil),  // 5: discopass.ConsultaReq
	(*ListaEventos)(nil), // 6: discopass.ListaEventos
	(*CompraReq)(nil),    // 7: discopass.CompraReq
	(*CompraResp)(nil),   // 8: discopass.CompraResp
	(*Ticket)(nil),       // 9: discopass.Ticket
	(*HistorialReq)(nil), // 10: discopass.HistorialReq
	(*ListaTickets)(nil), // 11: discopass.ListaTickets
	(*PagoReq)(nil),      // 12: discopass.PagoReq
	(*PagoResp)(nil),     // 13: discopass.PagoResp
	(*DBItem)(nil),       // 14: discopass.DBItem
	(*BacklogReq)(nil),   // 15: discopass.BacklogReq
	(*Backlog)(nil),      // 16: discopass.Backlog
}
var file_proto_discopass_proto_depIdxs = []int32{
	3,  // 0: discopass.ListaEventos.eventos:type_name -> discopass.Evento
	9,  // 1: discopass.ListaTickets.tickets:type_name -> discopass.Ticket
	3,  // 2: discopass.DBItem.evento:type_name -> discopass.Evento
	9,  // 3: discopass.DBItem.ticket:type_name -> discopass.Ticket
	3,  // 4: discopass.Backlog.eventos:type_name -> discopass.Evento
	9,  // 5: discopass.Backlog.tickets:type_name -> discopass.Ticket
	2,  // 6: discopass.Broker.RegistrarEntidad:input_type -> discopass.Registro
	3,  // 7: discopass.Broker.PublicarEvento:input_type -> discopass.Evento
	5,  // 8: discopass.Broker.ConsultarEventos:input_type -> discopass.ConsultaReq
	7,  // 9: discopass.Broker.ComprarEntrada:input_type -> discopass.CompraReq
	10, // 10: discopass.Broker.ObtenerHistorial:input_type -> discopass.HistorialReq
	15, // 11: discopass.Broker.SolicitarBacklog:input_type -> discopass.BacklogReq
	14, // 12: discopass.NodoDB.Escribir:input_type -> discopass.DBItem
	0,  // 13: discopass.NodoDB.LeerEventos:input_type -> discopass.Vacio
	10, // 14: discopass.NodoDB.LeerTickets:input_type -> discopass.HistorialReq
	0,  // 15: discopass.NodoDB.Salud:input_type -> discopass.Vacio
	12, // 16: discopass.Banco.ValidarPago:input_type -> discopass.PagoReq
	1,  // 17: discopass.Broker.RegistrarEntidad:output_type -> discopass.Ack
	4,  // 18: discopass.Broker.PublicarEvento:output_type -> discopass.PublicarResp
	6,  // 19: discopass.Broker.ConsultarEventos:output_type -> discopass.ListaEventos
	8,  // 20: discopass.Broker.ComprarEntrada:output_type -> discopass.CompraResp
	11, // 21: discopass.Broker.ObtenerHistorial:output_type -> discopass.ListaTickets
	16, // 22: discopass.Broker.SolicitarBacklog:output_type -> discopass.Backlog
	1,  // 23: discopass.NodoDB.Escribir:output_type -> discopass.Ack
	6,  // 24: discopass.NodoDB.LeerEventos:output_type -> discopass.ListaEventos
	11, // 25: discopass.NodoDB.LeerTickets:output_type -> discopass.ListaTickets
	1,  // 26: discopass.NodoDB.Salud:output_type -> discopass.Ack
	13, // 27: discopass.Banco.ValidarPago:output_type -> discopass.PagoResp
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_discopass_proto_init() }
func file_proto_discopass_proto_init() {
	if File_proto_discopass_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_discopass_proto_rawDesc), len(file_proto_discopass_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_discopass_proto_goTypes,
		DependencyIndexes: file_proto_discopass_proto_depIdxs,
		MessageInfos:      file_proto_discopass_proto_msgTypes,
	}.Build()
	File_proto_discopass_proto = out.File
	file_proto_discopass_proto_goTypes = nil
	file_proto_discopass_proto_depIdxs = nil
}
