// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: proto/discopass.proto

// Paquete de Protocol Buffers para el laboratorio DiscoPass.
// Aqui se definen TODOS los mensajes y servicios que viajan por gRPC
// entre las entidades del sistema (broker, productores, nodos DB,
// banco y consumidores).

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Broker_RegistrarEntidad_FullMethodName = "/discopass.Broker/RegistrarEntidad"
	Broker_PublicarEvento_FullMethodName   = "/discopass.Broker/PublicarEvento"
	Broker_ConsultarEventos_FullMethodName = "/discopass.Broker/ConsultarEventos"
	Broker_ComprarEntrada_FullMethodName   = "/discopass.Broker/ComprarEntrada"
	Broker_ObtenerHistorial_FullMethodName = "/discopass.Broker/ObtenerHistorial"
	Broker_SolicitarBacklog_FullMethodName = "/discopass.Broker/SolicitarBacklog"
)

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio que expone el Broker Central. Es el unico punto de coordinacion:
// lo usan productores, usuarios y los nodos DB (para pedir backlog).
type BrokerClient interface {
	RegistrarEntidad(ctx context.Context, in *Registro, opts ...grpc.CallOption) (*Ack, error)
	PublicarEvento(ctx context.Context, in *Evento, opts ...grpc.CallOption) (*PublicarResp, error)
	ConsultarEventos(ctx context.Context, in *ConsultaReq, opts ...grpc.CallOption) (*ListaEventos, error)
	ComprarEntrada(ctx context.Context, in *CompraReq, opts ...grpc.CallOption) (*CompraResp, error)
	ObtenerHistorial(ctx context.Context, in *HistorialReq, opts ...grpc.CallOption) (*ListaTickets, error)
	SolicitarBacklog(ctx context.Context, in *BacklogReq, opts ...grpc.CallOption) (*Backlog, error)
}

type brokerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerClient(cc grpc.ClientConnInterface) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) RegistrarEntidad(ctx context.Context, in *Registro, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Broker_RegistrarEntidad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) PublicarEvento(ctx context.Context, in *Evento, opts ...grpc.CallOption) (*PublicarResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicarResp)
	err := c.cc.Invoke(ctx, Broker_PublicarEvento_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) ConsultarEventos(ctx context.Context, in *ConsultaReq, opts ...grpc.CallOption) (*ListaEventos, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaEventos)
	err := c.cc.Invoke(ctx, Broker_ConsultarEventos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) ComprarEntrada(ctx context.Context, in *CompraReq, opts ...grpc.CallOption) (*CompraResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompraResp)
	err := c.cc.Invoke(ctx, Broker_ComprarEntrada_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) ObtenerHistorial(ctx context.Context, in *HistorialReq, opts ...grpc.CallOption) (*ListaTickets, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaTickets)
	err := c.cc.Invoke(ctx, Broker_ObtenerHistorial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) SolicitarBacklog(ctx context.Context, in *BacklogReq, opts ...grpc.CallOption) (*Backlog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Backlog)
	err := c.cc.Invoke(ctx, Broker_SolicitarBacklog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServer is the server API for Broker service.
// All implementations must embed UnimplementedBrokerServer
// for forward compatibility.
//
// Servicio que expone el Broker Central. Es el unico punto de coordinacion:
// lo usan productores, usuarios y los nodos DB (para pedir backlog).
type BrokerServer interface {
	RegistrarEntidad(context.Context, *Registro) (*Ack, error)
	PublicarEvento(context.Context, *Evento) (*PublicarResp, error)
	ConsultarEventos(context.Context, *ConsultaReq) (*ListaEventos, error)
	ComprarEntrada(context.Context, *CompraReq) (*CompraResp, error)
	ObtenerHistorial(context.Context, *HistorialReq) (*ListaTickets, error)
	SolicitarBacklog(context.Context, *BacklogReq) (*Backlog, error)
	mustEmbedUnimplementedBrokerServer()
}

// UnimplementedBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerServer struct{}

func (UnimplementedBrokerServer) RegistrarEntidad(context.Context, *Registro) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RegistrarEntidad not implemented")
}
func (UnimplementedBrokerServer) PublicarEvento(context.Context, *Evento) (*PublicarResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PublicarEvento not implemented")
}
func (UnimplementedBrokerServer) ConsultarEventos(context.Context, *ConsultaReq) (*ListaEventos, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarEventos not implemented")
}
func (UnimplementedBrokerServer) ComprarEntrada(context.Context, *CompraReq) (*CompraResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ComprarEntrada not implemented")
}
func (UnimplementedBrokerServer) ObtenerHistorial(context.Context, *HistorialReq) (*ListaTickets, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerHistorial not implemented")
}
func (UnimplementedBrokerServer) SolicitarBacklog(context.Context, *BacklogReq) (*Backlog, error) {
	return nil, status.Error(codes.Unimplemented, "method SolicitarBacklog not implemented")
}
func (UnimplementedBrokerServer) mustEmbedUnimplementedBrokerServer() {}
func (UnimplementedBrokerServer) testEmbeddedByValue()                {}

// UnsafeBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServer will
// result in compilation errors.
type UnsafeBrokerServer interface {
	mustEmbedUnimplementedBrokerServer()
}

func RegisterBrokerServer(s grpc.ServiceRegistrar, srv BrokerServer) {
	// If the following call panics, it indicates UnimplementedBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Broker_ServiceDesc, srv)
}

func _Broker_RegistrarEntidad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Registro)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).RegistrarEntidad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_RegistrarEntidad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).RegistrarEntidad(ctx, req.(*Registro))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_PublicarEvento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Evento)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).PublicarEvento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_PublicarEvento_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).PublicarEvento(ctx, req.(*Evento))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_ConsultarEventos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).ConsultarEventos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_ConsultarEventos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).ConsultarEventos(ctx, req.(*ConsultaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_ComprarEntrada_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompraReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).ComprarEntrada(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_ComprarEntrada_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).ComprarEntrada(ctx, req.(*CompraReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_ObtenerHistorial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistorialReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).ObtenerHistorial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_ObtenerHistorial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).ObtenerHistorial(ctx, req.(*HistorialReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_SolicitarBacklog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BacklogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).SolicitarBacklog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_SolicitarBacklog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).SolicitarBacklog(ctx, req.(*BacklogReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Broker_ServiceDesc is the grpc.ServiceDesc for Broker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discopass.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistrarEntidad",
			Handler:    _Broker_RegistrarEntidad_Handler,
		},
		{
			MethodName: "PublicarEvento",
			Handler:    _Broker_PublicarEvento_Handler,
		},
		{
			MethodName: "ConsultarEventos",
			Handler:    _Broker_ConsultarEventos_Handler,
		},
		{
			MethodName: "ComprarEntrada",
			Handler:    _Broker_ComprarEntrada_Handler,
		},
		{
			MethodName: "ObtenerHistorial",
			Handler:    _Broker_ObtenerHistorial_Handler,
		},
		{
			MethodName: "SolicitarBacklog",
			Handler:    _Broker_SolicitarBacklog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discopass.proto",
}

const (
	NodoDB_Escribir_FullMethodName    = "/discopass.NodoDB/Escribir"
	NodoDB_LeerEventos_FullMethodName = "/discopass.NodoDB/LeerEventos"
	NodoDB_LeerTickets_FullMethodName = "/discopass.NodoDB/LeerTickets"
	NodoDB_Salud_FullMethodName       = "/discopass.NodoDB/Salud"
)

// NodoDBClient is the client API for NodoDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio que expone cada Nodo DB. Solo lo usa el broker.
type NodoDBClient interface {
	Escribir(ctx context.Context, in *DBItem, opts ...grpc.CallOption) (*Ack, error)
	LeerEventos(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*ListaEventos, error)
	LeerTickets(ctx context.Context, in *HistorialReq, opts ...grpc.CallOption) (*ListaTickets, error)
	Salud(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*Ack, error)
}

type nodoDBClient struct {
	cc grpc.ClientConnInterface
}

func NewNodoDBClient(cc grpc.ClientConnInterface) NodoDBClient {
	return &nodoDBClient{cc}
}

func (c *nodoDBClient) Escribir(ctx context.Context, in *DBItem, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, NodoDB_Escribir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodoDBClient) LeerEventos(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*ListaEventos, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaEventos)
	err := c.cc.Invoke(ctx, NodoDB_LeerEventos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodoDBClient) LeerTickets(ctx context.Context, in *HistorialReq, opts ...grpc.CallOption) (*ListaTickets, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaTickets)
	err := c.cc.Invoke(ctx, NodoDB_LeerTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodoDBClient) Salud(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, NodoDB_Salud_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodoDBServer is the server API for NodoDB service.
// All implementations must embed UnimplementedNodoDBServer
// for forward compatibility.
//
// Servicio que expone cada Nodo DB. Solo lo usa el broker.
type NodoDBServer interface {
	Escribir(context.Context, *DBItem) (*Ack, error)
	LeerEventos(context.Context, *Vacio) (*ListaEventos, error)
	LeerTickets(context.Context, *HistorialReq) (*ListaTickets, error)
	Salud(context.Context, *Vacio) (*Ack, error)
	mustEmbedUnimplementedNodoDBServer()
}

// UnimplementedNodoDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodoDBServer struct{}

func (UnimplementedNodoDBServer) Escribir(context.Context, *DBItem) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Escribir not implemented")
}
func (UnimplementedNodoDBServer) LeerEventos(context.Context, *Vacio) (*ListaEventos, error) {
	return nil, status.Error(codes.Unimplemented, "method LeerEventos not implemented")
}
func (UnimplementedNodoDBServer) LeerTickets(context.Context, *HistorialReq) (*ListaTickets, error) {
	return nil, status.Error(codes.Unimplemented, "method LeerTickets not implemented")
}
func (UnimplementedNodoDBServer) Salud(context.Context, *Vacio) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Salud not implemented")
}
func (UnimplementedNodoDBServer) mustEmbedUnimplementedNodoDBServer() {}
func (UnimplementedNodoDBServer) testEmbeddedByValue()                {}

// UnsafeNodoDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodoDBServer will
// result in compilation errors.
type UnsafeNodoDBServer interface {
	mustEmbedUnimplementedNodoDBServer()
}

func RegisterNodoDBServer(s grpc.ServiceRegistrar, srv NodoDBServer) {
	// If the following call panics, it indicates UnimplementedNodoDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodoDB_ServiceDesc, srv)
}

func _NodoDB_Escribir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoDBServer).Escribir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoDB_Escribir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoDBServer).Escribir(ctx, req.(*DBItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodoDB_LeerEventos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vacio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoDBServer).LeerEventos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoDB_LeerEventos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoDBServer).LeerEventos(ctx, req.(*Vacio))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodoDB_LeerTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistorialReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoDBServer).LeerTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoDB_LeerTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoDBServer).LeerTickets(ctx, req.(*HistorialReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodoDB_Salud_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vacio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoDBServer).Salud(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoDB_Salud_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoDBServer).Salud(ctx, req.(*Vacio))
	}
	return interceptor(ctx, in, info, handler)
}

// NodoDB_ServiceDesc is the grpc.ServiceDesc for NodoDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodoDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discopass.NodoDB",
	HandlerType: (*NodoDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Escribir",
			Handler:    _NodoDB_Escribir_Handler,
		},
		{
			MethodName: "LeerEventos",
			Handler:    _NodoDB_LeerEventos_Handler,
		},
		{
			MethodName: "LeerTickets",
			Handler:    _NodoDB_LeerTickets_Handler,
		},
		{
			MethodName: "Salud",
			Handler:    _NodoDB_Salud_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discopass.proto",
}

const (
	Banco_ValidarPago_FullMethodName = "/discopass.Banco/ValidarPago"
)

// BancoClient is the client API for Banco service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio que expone el Banco USM. Solo lo usa el broker.
type BancoClient interface {
	ValidarPago(ctx context.Context, in *PagoReq, opts ...grpc.CallOption) (*PagoResp, error)
}

type bancoClient struct {
	cc grpc.ClientConnInterface
}

func NewBancoClient(cc grpc.ClientConnInterface) BancoClient {
	return &bancoClient{cc}
}

func (c *bancoClient) ValidarPago(ctx context.Context, in *PagoReq, opts ...grpc.CallOption) (*PagoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PagoResp)
	err := c.cc.Invoke(ctx, Banco_ValidarPago_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BancoServer is the server API for Banco service.
// All implementations must embed UnimplementedBancoServer
// for forward compatibility.
//
// Servicio que expone el Banco USM. Solo lo usa el broker.
type BancoServer interface {
	ValidarPago(context.Context, *PagoReq) (*PagoResp, error)
	mustEmbedUnimplementedBancoServer()
}

// UnimplementedBancoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBancoServer struct{}

func (UnimplementedBancoServer) ValidarPago(context.Context, *PagoReq) (*PagoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidarPago not implemented")
}
func (UnimplementedBancoServer) mustEmbedUnimplementedBancoServer() {}
func (UnimplementedBancoServer) testEmbeddedByValue()               {}

// UnsafeBancoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BancoServer will
// result in compilation errors.
type UnsafeBancoServer interface {
	mustEmbedUnimplementedBancoServer()
}

func RegisterBancoServer(s grpc.ServiceRegistrar, srv BancoServer) {
	// If the following call panics, it indicates UnimplementedBancoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Banco_ServiceDesc, srv)
}

func _Banco_ValidarPago_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BancoServer).ValidarPago(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banco_ValidarPago_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BancoServer).ValidarPago(ctx, req.(*PagoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Banco_ServiceDesc is the grpc.ServiceDesc for Banco service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Banco_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discopass.Banco",
	HandlerType: (*BancoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidarPago",
			Handler:    _Banco_ValidarPago_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discopass.proto",
}
